### ISSUE TITLE
Remove stringi dependency

### ISSUE THREAD

**Issue by robertzk** [avantcredit/r-servicetests#12]
It's a monster package, just use base R.

**Comment by peterhurford** [comment]
Stringi comes from stringr, and you import stringr, but I don't think you use it.

**Comment by peterhurford** [comment]
Maybe it's just an R package template problem?

**Comment by peterhurford** [comment]
It makes everything slow.

**Comment by khalidharun** [comment]
Thanks @kirillseva for purging stringr. Resolved.

**Comment by peterhurford** [comment]
Now we just have to remove it from every Hadley package.

**Comment by robertzk** [comment]
Yeah unbelievable.

**Comment by robertzk** [comment]
Wait this is a public repo.
